version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: fews_postgres
    environment:
      POSTGRES_USER: fews_user
      POSTGRES_PASSWORD: fews_password
      POSTGRES_DB: fews_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: fews_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
